let devices=[],wires=[],trees={},quickReference=[],currentTree=null,currentNodeId=null;
async function loadData(){try{devices=await fetch('data/devices.json').then(r=>r.json());wires=await fetch('data/wires.json').then(r=>r.json());trees=await fetch('data/trees.json').then(r=>r.json());quickReference=await fetch('data/quick-reference.json').then(r=>r.json());setupTabs();renderSymptoms();renderQuickReference();setupSearch();}catch(err){document.body.insertAdjacentHTML('beforeend',`<div class="panel bad"><h3>Data Load Error</h3><p>${err.message}</p><p>Verify data/devices.json, data/wires.json, data/trees.json, and data/quick-reference.json.</p></div>`);}}
function setupTabs(){document.querySelectorAll('.tab').forEach(btn=>{btn.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(b=>b.classList.remove('active'));btn.classList.add('active');document.querySelectorAll('.tabPanel').forEach(p=>p.classList.add('hidden'));document.getElementById(btn.dataset.tab+'Panel').classList.remove('hidden');document.getElementById('treePanel').classList.add('hidden');});});}
function renderSymptoms(){const el=document.getElementById('symptomButtons');el.innerHTML='';Object.keys(trees).forEach(key=>{const btn=document.createElement('button');btn.textContent=trees[key].title;btn.onclick=()=>startTree(key);el.appendChild(btn);});}
function startTree(key){currentTree=trees[key];currentNodeId=currentTree.start;document.getElementById('treePanel').classList.remove('hidden');document.getElementById('treeTitle').textContent=currentTree.title;renderNode();window.scrollTo({top:document.getElementById('treePanel').offsetTop,behavior:'smooth'});}
function renderNode(){const node=currentTree.nodes[currentNodeId];document.getElementById('stepCard').innerHTML=`<div class="card"><h3>${node.device}</h3><p class="meta"><strong>Question:</strong> ${node.question}</p><p class="meta"><strong>Expected:</strong> ${node.expected}</p><p class="meta"><strong>Drawing:</strong> ${node.drawing||''} ${node.line?'- Line '+node.line:''}</p><div class="choiceRow"><button onclick="answer('yes')">YES / VOLTAGE PRESENT / PASS</button><button onclick="answer('no')">NO / VOLTAGE ABSENT / FAIL</button></div></div>`;}
function answer(choice){const node=currentTree.nodes[currentNodeId];const next=node[choice];if(typeof next==='string'){currentNodeId=next;renderNode();return;}if(next&&next.result){document.getElementById('stepCard').innerHTML=`<div class="card ${choice==='yes'?'good':'bad'}"><h3>Result</h3><div class="result">${next.result}</div><button onclick="renderNode()">Back to Step</button></div>`;}}
function normalizeSearch(value){return String(value||'').toLowerCase().replace(/wire\s*/g,'').replace(/device\s*/g,'').replace(/relay\s*/g,'').replace(/[^a-z0-9]/g,'');}
function searchableText(obj){return [JSON.stringify(obj),obj.id,obj.wire,obj.description,obj.type,obj.drawing,obj.line,obj.location,obj.expectedVoltage,obj.normalState,obj.failureEffect].filter(Boolean).join(' ');}
function setupSearch(){const input=document.getElementById('searchInput');const btn=document.getElementById('searchBtn');btn.onclick=search;input.addEventListener('keydown',e=>{if(e.key==='Enter')search();});input.addEventListener('input',()=>{if(input.value.trim().length>=2)search();if(input.value.trim().length===0)document.getElementById('searchResults').innerHTML='';});document.getElementById('backBtn').onclick=()=>document.getElementById('treePanel').classList.add('hidden');}
function search(){const raw=document.getElementById('searchInput').value.trim();const q=raw.toLowerCase();const nq=normalizeSearch(raw);const el=document.getElementById('searchResults');if(!raw){el.innerHTML='<div class="card warn"><strong>Enter a device, wire number, alarm, or keyword.</strong></div>';return;}const deviceResults=devices.filter(d=>{const text=searchableText(d).toLowerCase();const norm=normalizeSearch(searchableText(d));return text.includes(q)||norm.includes(nq);});const wireResults=wires.filter(w=>{const text=searchableText(w).toLowerCase();const norm=normalizeSearch(searchableText(w));return text.includes(q)||norm.includes(nq);});if(deviceResults.length===0&&wireResults.length===0){el.innerHTML=`<div class="card warn"><h3>No match found</h3><p class="meta">Search entered: <strong>${raw}</strong></p><p class="meta">Try: <strong>CR6011</strong>, <strong>6091</strong>, <strong>Evis</strong>, <strong>Cooler</strong>, <strong>Debone</strong>, or <strong>ventilation</strong>.</p></div>`;return;}let html=`<div class="card"><strong>${deviceResults.length}</strong> device match(es), <strong>${wireResults.length}</strong> wire match(es) for "${raw}".</div>`;if(deviceResults.length){html+='<h3>Devices</h3>';html+=deviceResults.map(d=>`<div class="card"><h3>${d.id}: ${d.description}</h3><p class="meta"><strong>Type:</strong> ${d.type||''}</p><p class="meta"><strong>Drawing:</strong> ${d.drawing}, line ${d.line}</p><p class="meta"><strong>Location:</strong> ${d.location}</p><p class="meta"><strong>Normal:</strong> ${d.normalState}</p><p class="meta"><strong>Expected Voltage:</strong> ${d.expectedVoltage}</p><p class="meta"><strong>Upstream:</strong> ${(d.upstream||[]).join(' → ')}</p><p class="meta"><strong>Downstream:</strong> ${(d.downstream||[]).join(' → ')}</p><p class="meta"><strong>Fault Effect:</strong> ${d.failureEffect||''}</p></div>`).join('');}if(wireResults.length){html+='<h3>Wires</h3>';html+=wireResults.map(w=>`<div class="card"><h3>Wire ${w.wire}</h3><p class="meta"><strong>Drawing:</strong> ${w.drawing}</p><p class="meta"><strong>Line:</strong> ${w.line||''}</p><p class="meta"><strong>Description:</strong> ${w.description}</p><p class="meta"><strong>Expected:</strong> ${w.expectedVoltage}</p><p class="meta"><strong>From:</strong> ${w.from||''}</p><p class="meta"><strong>To:</strong> ${w.to||''}</p><p class="meta"><strong>Notes:</strong> ${w.notes||''}</p></div>`).join('');}el.innerHTML=html;}
function renderQuickReference(){document.getElementById('quickReference').innerHTML=`<table class="smallTable"><thead><tr><th>Symptom</th><th>First Check</th><th>Next Action</th></tr></thead><tbody>${quickReference.map(r=>`<tr><td>${r.symptom}</td><td>${r.firstCheck}</td><td>${r.next}</td></tr>`).join('')}</tbody></table>`;}
loadData();